### ISSUE TITLE
specific model

### ISSUE THREAD

**Issue by luismanson** [sellerie98/Coreboot-ThinkPad-T430#1]
Hello, can you tell what t430 did you flash? since most of the guides show t430S, maybe you can add machine type?

thanks!

**Comment by sellerie98** [comment]
Hi @luismanson, I flashed the not-S version of the T430.
What exactly do you mean with the machine type?

**Comment by luismanson** [comment]
The machine types are like different versions of the same model, its on the sticker with the serial number and says something like "M/T: xxxx" 
You can have for example a t430 with nvidia video and another with intel. one with glossy display, and another with a normal one.
here you have some reference: http://www.thinkwiki.org/wiki/Category:T430
Thats why i ask what specific model you have :)

I hope you understand my explanation

**Comment by sellerie98** [comment]
Hi @luismanson , sorry for the late answer.
Sadly, I bought my device without any S/N stickers attached anymore. I'm sorry.
Also, there is practically no reason for other configurations of this device to not work with CB.
